const spokenLanguages = [
    "Afrikaans",
    "Albanian",
    "Amharic",
    "Arabic",
    "Armenian",
    "Aymara",
    "Bashkir",
    "Basque",
    "Bengali",
    "Bislama",
    "Bosnian",
    "Breton",
    "Bulgarian",
    "Burmese",
    "Catalan",
    "Chewa",
    "Cherokee",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Estonian",
    "Farsi (Persian)",
    "Fijian",
    "Finnish",
    "French",
    "Galician",
    "Gaelic",
    "Georgian",
    "German",
    "Greek",
    "Gujarati",
    "Guarani",
    "Haitian Creole",
    "Hausa",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Igbo",
    "Inuktitut",
    "Irish",
    "Italian",
    "Japanese",
    "Javanese",
    "Kannada",
    "Kazakh",
    "Khmer",
    "Korean",
    "Kurdish",
    "Lao",
    "Latvian",
    "Lithuanian",
    "Macedonian",
    "Maori",
    "Malay",
    "Malayalam",
    "Mandarin Chinese",
    "Marathi",
    "Mongolian",
    "Nahuatl",
    "Nepali",
    "Norwegian",
    "Odia",
    "Pashto",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Quechua",
    "Romanian",
    "Russian",
    "Samoan",
    "Scots Gaelic",
    "Serbian",
    "Sinhala",
    "Slovak",
    "Somali",
    "Spanish",
    "Swahili",
    "Swedish",
    "Tagalog (Filipino)",
    "Tamil",
    "Telugu",
    "Thai",
    "Tibetan",
    "Tahitian",
    "Tok Pisin",
    "Tongan",
    "Turkish",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Vietnamese",
    "Welsh",
    "Wu Chinese",
    "Yue Chinese (Cantonese)",
    "Zulu"
  ];

  export default spokenLanguages;
  